#!/usr/bin/env bash
# Installs nginx on server web-01
# server listens on port 80
# redirection
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sed -i '/server_name _/a location /redirect_me { rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlw\u4? permanent; }' /etc/nginx/sites-available/default
sudo service nginx start
